# Generated by Django 4.2.2 on 2023-06-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=30)),
                ('razon_social', models.CharField(max_length=30)),
                ('cupo', models.IntegerField()),
                ('tiempo_credito', models.IntegerField()),
                ('nombre_comercial', models.CharField(max_length=100)),
            ],
        ),
    ]
